### ISSUE TITLE
OpenRailwayMap does not load without Flattr

### ISSUE THREAD

**Issue by Nakaner** [OpenRailwayMap/OpenRailwayMap#176]
api.flattr.com is down at the moment. That's why the web site is loaded only partially. My personal dirty work-around: add 
`127.0.0.1 api.flattr.com`
to `/etc/hosts` at my computer.

**Comment by Nakaner** [comment]
![flattr-down](https://cloud.githubusercontent.com/assets/3611273/6880571/b039b6b6-d538-11e4-94d5-fb33ebeff15f.png)

**Comment by rurseekatze** [comment]
Also have a look at #231.

**Comment by Nakaner** [comment]
#231 would fix this issue because if the Flattr icons is down, ORM is most propably down, too. :)

**Comment by DerDakon** [comment]
May be #445 is an improvement.

**Comment by rurseekatze** [comment]
Flattr was removed a year ago, so this is not relevant any more.
