### ISSUE TITLE
Static Flattr and Paypal buttons

### ISSUE THREAD

**Issue by rurseekatze** [OpenRailwayMap/OpenRailwayMap#231]
Remove the currently used Flattr and Paypal iframes and replace them by static images loaded from OpenRailwayMap server. This protects the user's privacy and makes website loading faster.

**Comment by DerDakon** [comment]
Flattr is gone, Paypal replaced with static link. Fixed?

**Comment by rurseekatze** [comment]
Yes, this was fixed by https://github.com/OpenRailwayMap/OpenRailwayMap/commit/333baeb8697da15b43c267e50403c1db872137f1 and https://github.com/OpenRailwayMap/OpenRailwayMap/commit/cfdcb854a1b4ddc5b5b91738a5086c1a1766c118.
