### ISSUE TITLE
Render platforms, including refs

### ISSUE THREAD

**Issue by bigbug21** [OpenRailwayMap/OpenRailwayMap#308]
It would be somewhat good to actually see the platforms of a station, along with their ref tags. Perhaps, at a later steigt, the height and surface tags might be used for further detailed rendering as well.

**Comment by PeterDRS** [comment]
Platforms or Platform_edges?

**Comment by bigbug21** [comment]
For a start? Platforms (railway=platforms and/or public_transport=platform)!

**Comment by PeterDRS** [comment]
The height is an attribute of the platform_edge, not of the whole platform. It can be different for two platform_edges.

**Comment by DerDakon** [comment]
Dupe of #190.
