### ISSUE TITLE
Check possibility to simplify import and update scripts

### ISSUE THREAD

**Issue by rurseekatze** [OpenRailwayMap/OpenRailwayMap#326]
According to https://github.com/openstreetmap/osm2pgsql/blob/master/README.md and http://wiki.openstreetmap.org/w/index.php?title=O5m&diff=prev&oldid=1205672, osm2pgsql is now able to read o5m file directly. Check if this allows it to simplify the import and update process due to unnecessary conversions of file formats.

**Comment by DerDakon** [comment]
Is osc good enough?

**Comment by rurseekatze** [comment]
This is not relevant any more after the update process was simplified.

Earlier when the update process was mainly based on file operations with osmfilter/osmupdate/osmconvert, reading o5m with osm2pgsql could have meant a better performance by reducing the number of file format conversions.
