### ISSUE TITLE
Smaller width for "Nebengleise" in speed map

### ISSUE THREAD

**Issue by ghost** [OpenRailwayMap/OpenRailwayMap#334]
Tracks where no trains drive (only shunting) - in Germany so called "Nebengleise" - are usually not tagged with a maxspeed, as the shunting speed is 25 km/h or 40 km/h. It would be confusing having these speeds shown - I think it is right not to tag any speed to a "Nebengleis".

But it would be good to see it on the speed map that these are "Nebengleise", meaning to show them with a lower width.

**Comment by JJJWegdam** [comment]
Dear Ghost,

please consider policies in other nations. In the Netherlands, all available (not blocked by buffer_stops) tracks are required to have a maxspeed-tag in the database. For shunting tracks, the speed limit is based on the angles of it's switches or lower (based on for example noise regulations). Therefore I disagree that these tracks should not be tagged if information is available.

I do agree though on giving tracks different widths based on functions like in Mapnik. Functions don't have anything to do with speed limits, but different widths can make maps easier to read.

**Comment by DerDakon** [comment]
The information about the "track class" is now easily available in the styles, so this shouldn't be too hard to implement. I'll give it a try.
