### ISSUE TITLE
Remove PBF format from import/update process

### ISSUE THREAD

**Issue by rurseekatze** [OpenRailwayMap/OpenRailwayMap#396]
Do not store data in PBF format any more. Using PBF in the toolchain saves some disk storage, but needs some expensive conversion steps which are one bottleneck of the process. Storing the data in o5m Format needs more storage, but makes some of these conversion steps obsolete.

This needs some tests on the server before implementation.

**Comment by DerDakon** [comment]
The usage of pbf is now limited to the import process. Can this be closed?

**Comment by rurseekatze** [comment]
The import/update toolchain was simplified, most of the file-based steps have been removed. This issue can be closed.
