### ISSUE TITLE
Asian characters are not shown on map

### ISSUE THREAD

**Issue by sb12** [OpenRailwayMap/OpenRailwayMap#408]
Asian characters like Korean, Japanese or Chinese in station names are not shown on the map

Examples:
- [Seoul, Korea](http://www.openrailwaymap.org/?lang=en&lat=37.55304948654156&lon=126.99203968048096&zoom=14&style=standard)
- [Tokyo, Japan](http://www.openrailwaymap.org/?lang=en&lat=35.706551648963575&lon=139.77308750152588&zoom=14&style=standard)
- [Beijing, China](http://www.openrailwaymap.org/?lang=en&lat=39.909834989900844&lon=116.44258975982667&zoom=14&style=standard)

**Comment by rurseekatze** [comment]
The bug is related to the used rendering software [node-tileserver](https://github.com/rurseekatze/node-tileserver), so I [moved your bug report](https://github.com/rurseekatze/node-tileserver/issues/72) over to that repository.
