### ISSUE TITLE
Crossing icons rendered semi-transparent

### ISSUE THREAD

**Issue by rurseekatze** [OpenRailwayMap/OpenRailwayMap#440]
In some cases the crossing icons added in #431 are rendered semi-transparent. The problem seems to occur randomly and in various browsers.

Example: http://www.openrailwaymap.org/canvas.php?lat=51.213631512329655&lon=6.781525611877441&zoom=14&style=standard

**Comment by DerDakon** [comment]
Seems to be gone with the new stack.

**Comment by Nakaner** [comment]
JOSM does not have this issue at all.
