### ISSUE TITLE
Distinguish French TVM signalling versions

### ISSUE THREAD

**Issue by STemplar** [OpenRailwayMap/OpenRailwayMap#563]
Can we make a distinction in the French TVM (high speed) TPS? They currently come in two versions: TVM-300 and TVM-430.

**Comment by JJJWegdam** [comment]
We indeed don't distinguish that yet. In order to do it properly we need to know wether the TVM-300 and TVM-430 can exist next to eachother. Do you have any information on that, @STemplar? Thank you in advance

**Comment by DerDakon** [comment]
This is a tagging issue, so it should be brought up to the mailing list. This tracker is only about the website, i.e. implementation issues.
