### ISSUE TITLE
Add support for HTTPS to API

### ISSUE THREAD

**Issue by rurseekatze** [OpenRailwayMap/OpenRailwayMap#564]
Extend the API so that it supports HTTPS.

**Comment by DerDakon** [comment]
I wonder if it is enough to teach the Apache instance that acts as proxy to support HTTPS.

**Comment by bivald** [comment]
As a side note I'm hosting OpenRailWayMap API+Tiles over HTTPS(http2) using Nginx as proxy, so it's definitely should be enough to teach the Apache instance HTTPS. I would suggest also looking into http2 (mod_http2 in Apache) since http2 could speed up this type of operations

**Comment by DerDakon** [comment]
Would you mind doing a PR where you add instructions how to set this up to INSTALL.md?

**Comment by rurseekatze** [comment]
HTTPS support was enabled with https://github.com/OpenRailwayMap/server-admin/issues/2. Currently there is no need for HTTPS support as part of the API code, as most users including openrailwaymap.org will use it behind a reverse proxy like Apache or nginx.

**Comment by rurseekatze** [comment]
Memo: Update the documentation in INSTALL.md and describe the configuration of HTTPS.
