### ISSUE TITLE
Computed timestamp wrong

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/OpenRailwayMap#573]
The website currently says "27.01.2017 18:36, more than 1 hour ago" in my Chromium (it's 18:57). From a quick glance at the code it should show some minutes. I suspect it is a timezone thing (UTC+1).

**Comment by rurseekatze** [comment]
I think this was already fixed by my rewrite of the timestamp calculation in https://github.com/OpenRailwayMap/OpenRailwayMap/commit/7bfbb9020caf9efbf0989ecf1f8ed86cf97ae993.
