### ISSUE TITLE
Use route=railway relation name and ref

### ISSUE THREAD

**Issue by Penegal** [OpenRailwayMap/OpenRailwayMap#652]
In some cases, especially disused and abandoned railways, the railway name and ref is in a `route=railway` relation of which the railway is a member. In such cases, it could be useful to render the name and ref of the relation instead of the ones of the way, because, in much cases, the tracks have been replaced with highways, whose name and ref are rendered instead.

**Comment by DerDakon** [comment]
Use abandoned:name and abandoned:ref instead. We intentionally drop relations at the moments because they cause other hassle with the rendering.

**Comment by Penegal** [comment]
Ok, I understand; thanks for your answer.
