### ISSUE TITLE
Low zoom levels don't update anymore or don't update often enough

### ISSUE THREAD

**Issue by JJJWegdam** [OpenRailwayMap/OpenRailwayMap#657]
In [this changeset](https://www.openstreetmap.org/changeset/66868161), I tagged the Bentheimer Eisenbahn as railway without train protection. On [zoom level 17](https://www.openrailwaymap.org/?lang=null&lat=52.60949136632665&lon=6.848081946372986&zoom=17&style=signals) we can see the change rendered correctly. On [zoom level 11](https://www.openrailwaymap.org/?lang=null&lat=52.47776193184992&lon=7.032279968261719&zoom=11&style=signals) however, we see the map as before the changeset has happened. _The changeset was three months ago._

Similar stuff is happening while I'm tagging the Balkan railway ways with maxspeeds and signalling systems ([example](https://www.openstreetmap.org/changeset/69480453)).

**Comment by JJJWegdam** [comment]
For now I'll manually clear the cache per dirty tile, through for example
https://c.tiles.openrailwaymap.org/signals/5/16/10.js/dirty

**Comment by bigbug21** [comment]
This issue has been around for at least half a year, see https://lists.openrailwaymap.org/pipermail/openrailwaymap/2019-January/000598.html.

**Comment by jorgen9** [comment]
Same for me. Have done abandoned railways in Sweden.  But in just zoom level 17 I see the abandon railways. I change it for 4 days ago. The other abandon railways (inserted before me) 
I can see in zoom level  9 .  Very annoying error. 
You cant know it is a abandoned railway know if you already knew about it before

**Comment by EckhardM** [comment]
I am still experiencing this issue: on https://www.openrailwaymap.org/?lang=null&lat=54.13036644919398&lon=12.078083753585815&zoom=16&style=standard you see abandoned railways only partly. I deleted the crane rails on https://www.openrailwaymap.org/?lang=null&lat=54.16212616759345&lon=12.091537714004517&zoom=16&style=standard but they are still visible. That effects all levels.

**Comment by DerDakon** [comment]
This should be solved meanwhile. If not, please file a new issue in https://github.com/OpenRailwayMap/server-admin.
