### ISSUE TITLE
validator and styles disagree about tagging of usage=military + service

### ISSUE THREAD

**Issue by DerDakon** [OpenRailwayMap/OpenRailwayMap#664]
https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/styles/standard.mapcss#L186

```
way[usage=military][!service].tracks,
```

https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss#L12

``´
way[railway][usage][usage!=industrial][usage!=military][service]
```

Fix in either direction is easy, we just need to agree which one is correct.

**Comment by Nakaner** [comment]
We say that `usage=*` should not be used together with `service=*` except for industrial and military lines. Therefore, the validator is correct, the map style (including the CartoCSS) needs to be changed.
