### ISSUE TITLE
Funicular railway=station without name

### ISSUE THREAD

**Issue by fansanelli** [OpenRailwayMap/OpenRailwayMap#675]
Hello,

I experienced this error:

railway=station without name

With a funicular station:
https://wiki.openstreetmap.org/wiki/Tag:station=funicular

due to:
https://github.com/OpenRailwayMap/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss#L709-L738

Does the train station rule still apply?
Many thanks,
Best regards
Francesco

**Comment by Nakaner** [comment]
Funicular stations which are often just called "Valley Station" and "Top Station" are edge cases. One can have the opinion that they should not have a `name` tag in OSM. If you know how to distinguish them with JOSM validator rules from other stations, I am happy to accept a pull request.

**Comment by fansanelli** [comment]
> Funicular stations which are often just called "Valley Station" and "Top Station" are edge cases. One can have the opinion that they should not have a `name` tag in OSM. If you know how to distinguish them with JOSM validator rules from other stations, I am happy to accept a pull request.

Please find it:

https://github.com/OpenRailwayMap/OpenRailwayMap/pull/676

let me know what you think.
Cheers
Francesco

**Comment by Nakaner** [comment]
Fixed by #676
