### ISSUE TITLE
 "lanes=* is used for highways, not railways"

### ISSUE THREAD

**Issue by frodrigo** [OpenRailwayMap/OpenRailwayMap#682]
Report of https://github.com/osm-fr/osmose-backend/issues/780

"lanes=* is used for highways, not railways" - it suggests an error for a way tagged:
```
disused:railway = tram
highway = tertiary
railway = disused
lanes=2
```

There is a "highway=*" tag so it shouldn't suggest an error.

**Comment by DerDakon** [comment]
Duplicate of #660.
