### ISSUE TITLE
Electrification Layer: Track which is under construction is displayed as "electrified"

### ISSUE THREAD

**Issue by twatzl** [OpenRailwayMap/OpenRailwayMap#718]
Hi, 

another issue while trying out electrification layer is that track which is currently under construction is shown as already electrified:

![image](https://user-images.githubusercontent.com/18753370/111078641-c9f48a80-84f6-11eb-88ce-d6a0908dc7c0.png)
![image](https://user-images.githubusercontent.com/18753370/111078643-d5e04c80-84f6-11eb-8d33-2f2e350ad119.png)
![image](https://user-images.githubusercontent.com/18753370/111078671-fa3c2900-84f6-11eb-83bd-518fdb2fb89f.png)

Best,
Tobi

**Comment by DerDakon** [comment]
Wrong repo, and already reported as OpenRailwayMap/OpenRailwayMap-CartoCSS#47.
