### ISSUE TITLE
Electrification layer: disregard "proposed:*"

### ISSUE THREAD

**Issue by pzorin** [OpenRailwayMap/OpenRailwayMap#719]
I would suggest disregarding "proposed:electrified" and all related tags. As an example, currently the lines Ulm-Friedrichshafen and Radolfzell-Friedrichshafen look almost the same, but the former will be completed this year and for the latter there are no concrete electrification plans at all.

**Comment by Nakaner** [comment]
That's not an issue of the map style but of the data. Some people use `proposed` for ideas a politician has spoken about although the planning itself has not been funded yet.

In Germany, there is a rough consensus that `proposed` should not be used before the Planfeststellungsverfahren has started. I do not know the current status between Friedrichshafen and Radolfzell. If the Planfeststellungsverfahren has not been started yet, I suggest to just delete the `proposed:electrified=*` tags (and associated tags for voltage and frequency).

**Comment by pzorin** [comment]
Thanks, I've fixed that particular issue with data.
It would still be good to make dashes for `proposed` electrification sparser, they look too similar to `construction` now.

**Comment by DerDakon** [comment]
That is a problem that happens because there are often 2 or more tracks besides each other, and the actual way segments tend to get very short. Then things start to overlap in the renderer. This has been a problem basically forever with no good solution being available yet.

**Comment by pzorin** [comment]
Shortness of the way segments could be partially overcome by aligning dashes so that each segment starts in the middle of a gap between 2 dashes like this: `..-....-....-....` (this is how the standard style on openstreetmap.org seems to render railway lines). I believe that this will produce visually better results than the current solution, which seems to be `-....-....-....`.
