### ISSUE TITLE
Stillwater on New Zealand's South Island is misspelled as "Stilwater"

### ISSUE THREAD

**Issue by hmmueller** [OpenRailwayMap/OpenRailwayMap#776]
Here is an image (although form 1992) that shows that the railway writes it with two L's:

![Stillwater, 1992](https://www.hmmueller.de/DVDF_x1000/79-035.jpg) 

H.M.

**Comment by DerDakon** [comment]
This is only a data issue. Please either edit it in OpenStreetMap data yourself or go to https://openstreetmap.org and add a note at the right position so someone else can have a look.
