### ISSUE TITLE
Electrification rendering is missing for usage=freight

### ISSUE THREAD

**Issue by MaartenDeen** [OpenRailwayMap/OpenRailwayMap#778]
When a railway is tagged with usage=freight, then the electrification is not rendered.
Examples, [this way](https://www.openstreetmap.org/way/28496383), [map](https://www.openrailwaymap.org/?style=electrified&lat=50.5407&lon=4.2097&zoom=15) and [that way](https://www.openstreetmap.org/way/199508259), [map](https://www.openrailwaymap.org/?style=electrified&lat=50.45598079054058&lon=4.672611951828003&zoom=16)

**Comment by DerDakon** [comment]
There is no such thing as usage=freight, see the [wiki](https://wiki.openstreetmap.org/wiki/Railways#Types_of_railway_line).

**Comment by MaartenDeen** [comment]
Is there a reason why you would not render usage types that you don't recognize? Or in other words: are there usage types that you don't want to render, and why is that?

**Comment by DerDakon** [comment]
Exactly for the reason to nag people to fix their tagging. This has been in the code right from the start.

The correct tagging would btw. be ```railway:traffic_mode=freight```.

**Comment by MaartenDeen** [comment]
So when a new tag would be introduced you have to change the code. That does not seem very productive. Is this a QA tool or a visualization tool?

**Comment by DerDakon** [comment]
Both, intentionally ;)

It's much easier to write rules for the correct tagging than filter out known error cases. And we are updating the rendering rules basically all the time to cover new cases like signals and so on.
