### ISSUE TITLE
Electrification and Track Gauge data not updating in mid zooming levels

### ISSUE THREAD

**Issue by arnavbhate** [OpenRailwayMap/OpenRailwayMap#786]
An example for electrification is [Konkan Railway](https://www.openrailwaymap.org/?style=electrified&lat=16.165218468867508&lon=73.77250671386717&zoom=10) which was marked as electrified a month and half back but at this zoom level it still shows up as unelectrified. Upon zooming in or zooming out it becomes shown as electrified.

For track gauge an example is [Mumbai Metro](https://www.openrailwaymap.org/?style=gauge&lat=19.113704820498107&lon=72.9818344116211&zoom=11) which is 1435 mm gauge (both actually and in OpenStreetMap) but most of it shows up as 1676 mm gauge. Upon zooming in, it is shown correctly as standard gauge and under construction.

**Comment by DerDakon** [comment]
This is the same as https://github.com/OpenRailwayMap/server-admin/issues/33, see especially https://github.com/OpenRailwayMap/server-admin/issues/33#issuecomment-1149497715.
