### ISSUE TITLE
Data not updating on lower zoom levels

### ISSUE THREAD

**Issue by mmosteck** [OpenRailwayMap/OpenRailwayMap#790]
Changes made to the tracks (max speed, signalling etc.) do not update on lower zoom levels.

I updated some speeds **4 months ago** and they are still not reflected. 

After zooming in, the data is correct.

**Comment by Nakaner** [comment]
Fixed by https://github.com/OpenRailwayMap/server-admin/commit/335ed26bd86817f873830808aa35a4d480b59a56

Tiles on zoom level 0 to 9 are rerendered every 30 days. Zoom levels 10 and larger are put into the rerendering queue if there are node or way edits inside their area.
