### ISSUE TITLE
Add Italian SCMT signalling system to render and legend

### ISSUE THREAD

**Issue by davide84** [OpenRailwayMap/OpenRailwayMap#791]
Hi, I would like to see the Italian SCMT signalling system in Openrailwaymap. The system has been extended to more than 10.000 km of lines, won't be replaced soon and there is an established tag in OSM (railway:scmt).

I found this old issue
https://github.com/OpenRailwayMap/OpenRailwayMap/issues/695
where the suggestion was to contribute to CartoCSS; however I am not sure about that solution, because in CartoCSS I don't see the French signalling system which is visible in ORM; e.g. there are no references to KVB or TWM in
https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/blob/master/train_protection.mss
so maybe the changes should go to another place?

I could prepare a Pull Request to contribute myself to the necessary changes, what is the best way to go? :-)

**Comment by DerDakon** [comment]
The file you pointed to is used for the actual tiles on the website. Things that are shown in the legend or when editing in JOSM use the MapCSS in this repository.

**Comment by davide84** [comment]
Ok, thanks. So I would need to do a PR in that repo, to have the tag rendered, and then a PR on this repo, to have the proper legend. I will try, in this order. I'll pick a color that does not interfere with other things already displayed.
Thanks!

**Comment by davide84** [comment]
The item appeared today in the legend, rendering is also gradually appearing in tiles. Thank you!
