### ISSUE TITLE
Two RSS links and one main link

### ISSUE THREAD

**Issue by jidanni** [OpenRailwayMap/OpenRailwayMap#807]
On the front page of this GitHub, we see  links

OpenRailwayMap Blog (RSS de en)

The RSS is divided into two languages, but not the main blog. Odd. In fact the main blog has a header in German and then content below it is in English.

**Comment by Nakaner** [comment]
The language of the blog depends on your browser settings. We offer most posts in both languages. You can access the blog and the RSS feeds with and without a language parameter.
