### ISSUE TITLE
Add rendering for train protection in Sweden

### ISSUE THREAD

**Issue by tomastomas75** [OpenRailwayMap/OpenRailwayMap#824]
Looking at the map style "signalling", all railways in sweden are marked as "no information available" (except for Bottniabanan which is tagged railway:etcs=yes). Which is not true. The information IS available.

Most of swedish railways do have the ATC system (automatic train control), since the 1980's and are also tagged 

railway:atc=yes
or
railway:atc = no
(where "no" means "no protection system", not "no information available")

This is also, as I understand, tagged in the same way as german railways which have:

railway:pzb=yes
railway:lzb=yes

..and others. 

I guess it wouldn't be TOO much work to add a legend for swedish ATC (and norwegian, which is identical). Just look for the tag "railway:atc=yes" end give it a nice colour.

**Comment by bjoernma** [comment]
Does anybody know whether there is already a (tagging) distinction between the US / japanese / norwegian ATC system as they sound to be (technically) different in wikipedia. 
I think that will be an even bigger problem for the "no protection" case.
If there would be a distinction in tagging, my next question for sweden/norway would be about an complete(!) list of possible train control systems in those two countries. 
I think a country based rendering is not (yet?) possible?

**Comment by tomastomas75** [comment]
I don't know anything about US or Japan, but in Sweden there are only ATC or ETCS, or no train protection* at all.

Norway has the same ATC system as Sweden, and I dont THINK there is any other systems there, but I'll check. 

*) Manual systems, as "calling the other end of the line to receive authorization" counts as "no protection".

**Comment by DerDakon** [comment]
ATC should now be rendered.

**Comment by tomastomas75** [comment]
Excellent @DerDakon, thank you!
