### ISSUE TITLE
wrong render order for no train protection

### ISSUE THREAD

**Issue by Bauer33333** [OpenRailwayMap/OpenRailwayMap#827]
The line for no train protection seems to be rendered over positive train control making areas with PTC but not an other protection system look like they have none at all. 
Here is an example: https://www.openrailwaymap.org/?style=signals&lat=39.9910294918822&lon=-75.17714738845825&zoom=15
Here the railway:atc=no is rendered over the railway:ptc=yes making it invisible. 
The no train protection should always be below all other protection systems, similiar to how ETCS seems to be over all others

**Comment by freaktechnik** [comment]
This seems like a CSS rule specificity issue in
https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/blob/b6b92d1f4284c25f28f04cec4fbf1c8c0d52b059/train_protection.mss#L62-L68
where this rule wins over the simpler rules, because it depends on more than one property selector per condition?

**Comment by Bauer33333** [comment]
It doesn't happen with the french system that has three conditions, ETCS construction renders fine over it, so it propably is caused by the "and" conditions, not the "or" conditions.
I don't have any ideas how to work around that, assuming you can't do stuff like: render this only if non of the others is present?
Or you add ptc=no to the list of requirements for no train protection, but then all of Portugal, Spain and Scandinavia would need that tag, what doesn't seem right to me.

It's a shame we don't have something like railroad:train_protection=no, this would solve a lot of issues, the current system is just making educated guesses.

**Comment by freaktechnik** [comment]
A solution might be to change those selectors to `["rank"=1]`, which should still only select routes that the ranking function deems as having no train protection.

**Comment by Bauer33333** [comment]
I'm afraid I don't know how to use that, I've never touched CSS in my life and the last time html has been a few years, too
Just in front of each statement like this?

`   ["rank"=1]["pzb"="no"]["lzb"="no"]["etcs"="no"]["construction_etcs"="no"],
    ["rank"=1]["atb"="no"]["etcs"="no"]["construction_etcs"="no"],
    ["rank"=1]["atc"="no"]["etcs"="no"]["construction_etcs"="no"],
    ["rank"=1]["kvb"="no"]["tvm"="no"]["etcs"="no"]["construction_etcs"="no"],
    ["rank"=1]["scmt"="no"]["etcs"="no"]["construction_etcs"="no"] {
      line-color: @no_train_protection_color;
    }
    ["rank"=0]["pzb"="yes"] {
      line-color: @pzb_color;
    }
   ["rank"=0]["lzb"="yes"] {
      line-color: @lzb_color;
    }`

I would apprechiate if someone else could try a few things, I feel like this is less work than teaching me first

**Comment by Bauer33333** [comment]
> Hi! I just wanted to mention that I had a similar issue fixed with a PR: [OpenRailwayMap/OpenRailwayMap-CartoCSS#93](https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/pull/93) this PR resulted in the ["construction_etcs"="no"] condition reported in the post above.

How does this work eg. in this area: https://openrailwaymap.org/?style=signals&lat=42.15362100375332&lon=-72.60935068130493&zoom=15
There are no etcs tags at all, so it doesn't fullfill any of the conditions, but is rendered as no train protection?

Are there even more issues since this segment seems to do something that isn't even in the CSS?

> In any case, this may very well be another issue that would be automatically solved if this discussion https://wiki.openstreetmap.org/wiki/Proposal:Railway:train_protection moves forward, which I really really hope :) because the current system is already not scaling well, and we mostly have just Europe tagged, and not all of it.

Probably a bit offtopic, but how would one move that forward, what is missing for it to be approved? How are decisions made in general, there doesn't seem to be someone in power or a voting system. I don't believe I could just write the new way of tagging into the wiki and the issue is solved?

**Comment by davide84** [comment]
> How does this work eg. in this area: https://openrailwaymap.org/?style=signals&lat=42.15362100375332&lon=-72.60935068130493&zoom=15 There are no etcs tags at all, so it doesn't fullfill any of the conditions, but is rendered as no train protection?

The tag there is railway:atc=no, I suppose that's the reason. And if I understand correctly, it's the right behavior.

> Are there even more issues since this segment seems to do something that isn't even in the CSS?

I think it matches line 64 here https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/blob/master/train_protection.mss:
> ["atc"="no"]["etcs"="no"]["construction_etcs"="no"]
the missing ETCS tags are interpreted as "no". But I had to think twice before answering, the current logic is getting hard to handle.

> Probably a bit offtopic, but how would one move that forward, what is missing for it to be approved? How are decisions made in general, there doesn't seem to be someone in power or a voting system. I don't believe I could just write the new way of tagging into the wiki and the issue is solved?
Good question :) I assumed that if there was a proposal there also was a process... I think that at some level yes, there must be a group of users who say "this is the way we do it".

I think that, assuming we (meaning 5-6 active contributors to ORM) agree on the wiki proposal, it would be reasonable to just start adding the new tagging system everywhere. This would not break any other software using the current tagging and could potentially be done automatically with a bot (I'm willing to look into it).
After that "we" could go around and explain how ORM is doing things and why, and removing old tags at national or regional level. This would take years, no rush.

I understand this discussion should probably happen elsewhere - I'm happy to continue there or even just stop, just let me/us know :-)

**Comment by Bauer33333** [comment]
> the missing ETCS tags are interpreted as "no". 

If this is true for ctc and ptc, too, the initial issue should be fixed pretty easily. Just ["ptc"="no"],["acses"="no"] and ["ctc"="no"] needs to be added as an additional condition in line 64. 
It wouldn't break the no train protection in Portugal and Scandinavia due to defaulting ctc, acses and ptc to no if only atc is found, so no need to add the ...=no tags in Iberia and Scandinavia

**Comment by davide84** [comment]
Yes but you see the point? For every signalling system "S" we should add a condition ["S"="no"] on multiple lines... with exponential possibilities of making mistakes. I'm not really happy to go that way, that's why I'm trying to push a bit with the re-tagging proposal.

**Comment by freaktechnik** [comment]
I think using just 
```less
 ["rank"=1] {
      line-color: @no_train_protection_color;
 }
```
as I tried to suggest before would be clear enough for now.

**Comment by davide84** [comment]
Sorry for having missed the hint before. I checked the code, the "rank"=1 solution could work. It could actually be quite a smart solution, since it delegates almost completely the messy logic to the sql functions instead of duplicating it. There should not be a 1:1 match between ranks and signalling systems, but it should always be possible to rely on rank0 = no info and rank1 = no protection.

We still have the mess in the sql part, though, but this rank thing would still be an improvement. If nobody volunteers, I'll try to do some local test and maybe a PR in the next days.

**Comment by Bauer33333** [comment]
This has been fixed by merging the pull request mentioned above.
The track I gave as an example is now turning red: 
![Screenshot_20231004-224150_Firefox](https://github.com/OpenRailwayMap/OpenRailwayMap/assets/103360469/87ce6a71-a26c-48d4-8d63-25c43cd4fd73)
