### ISSUE TITLE
usage=tourism renders inconsistently

### ISSUE THREAD

**Issue by Darrman** [OpenRailwayMap/OpenRailwayMap#829]
I've been editing the map mainly on the island of Ireland and I've run into some oddities with heritage railways.
The Downpatrick and County Down Railway largely doesn't render [(North Line, way 598123535)](https://www.openstreetmap.org/way/598123535). The service tracks render, which lack usage tags as appropriate.
Yet the [Peatlands Park Railway](https://www.openstreetmap.org/way/371749441), [Cavan and Leitrim Railway](https://www.openstreetmap.org/way/151909764), and [Waterford and Suir Valley Railway](https://www.openstreetmap.org/way/488317958) all render as branch lines. These three lines are all narrow gauge (railway=narrow_gauge), while the DCDR is Irish standard gauge (railway=rail). All four of these lines are tagged as usage=tourism.

Examples of inconsistent behaviour can be found in Britain too. The narrow gauge [Ffestiniog Railway](https://www.openstreetmap.org/way/137213261) renders, but the standard gauge [Cambrian Heritage Railway](https://www.openstreetmap.org/way/757746295) does not, to use Welsh examples. In England, this section of the [Severn Valley Railway](https://www.openstreetmap.org/way/60577116) doesn't render as it has usage=tourism, but the rest of the line has no usage at all and renders as a black line.

**Comment by divulgacheur** [comment]
I agree with you, I have found the same behavior in France railways : `railway=rail` with `usage=tourism` are not rendered, [like this one](https://www.openstreetmap.org/way/45233866) [that is not visible on OpenRailwayMap.](https://www.openrailwaymap.org/?lat=45.2195&lon=4.295700000000011&zoom=12)

**Comment by DerDakon** [comment]
This is an issue in the CartoCSS style, not in the older Mapnik styles only used for JOSM rendering these days.

https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/issues/7
