### ISSUE TITLE
Visualize Spanish train protection system ASFA

### ISSUE THREAD

**Issue by Robot8A** [OpenRailwayMap/OpenRailwayMap#834]
The tagging is already detailed at the tagging page on OSM Wiki: https://wiki.openstreetmap.org/wiki/OpenRailwayMap/Tagging#Train_protection_systems

Overpass query:
https://overpass-turbo.eu/s/1uKX

As seen, some lines are tagged already on OSM (even if most are missing). However, in OpenRailwayMap, these lines get visualized as no information. Example: https://openrailwaymap.org/?style=signals&lat=40.464580539410264&lon=-3.783330917358398&zoom=13

**Comment by STemplar** [comment]
This issue can be closed.

**Comment by DerDakon** [comment]
Done in #848.
