### ISSUE TITLE
Show multiple tracks at lower Zoom levels

### ISSUE THREAD

**Issue by jidanni** [OpenRailwayMap/OpenRailwayMap#837]
For [multiple  tracks](https://www.openrailwaymap.org/index.php?style=standard&lat=42.52414117744632&lon=-87.91654855012894&zoom=16) we observe:

Other layers, like Openstreetmap,  Opentopomap, show there are two rail lines at a much lower zoom level than the openrailwaymap layer.

Users overlaying those maps are scratching their heads, "I thought there were both  northbound and  southbound rails here. Why do I only see a single orange Line instead of a double orange line?"

Please have your tiles show multiple lines at the same zoom level that common other layers do.

No, even using thicker lines would still be confusing. Just show individual thin lines.

Don't misunderstand me.  I am saying that two metal rails should equal one orange line on the map. And four metal rails should equal two orange lines on the map...

**Comment by DerDakon** [comment]
This is nothing that is actively hidden, it's just that the lines are too thick so they will join at lower zoom levels, hiding that there are multiple parallel lines.
