### ISSUE TITLE
Change layer "Signals"to "Signals and Train Protection System"?

### ISSUE THREAD

**Issue by STemplar** [OpenRailwayMap/OpenRailwayMap#845]
Signals and Train Protection Systems are mostly two separate systems. In the past train networks were utilised with a signalling system and later a TPS was added for protection. In the Netherlands the systems NS'54 (Signalling) and ATB-EG (TPS) are used together and the combination is called NS'54 ATB-EG. Only in newer systems like ETCS (part of ERTMS), cabin signalling and TPS is integrated in one system.

**Comment by Nakaner** [comment]
solved by the linked pull request
