### ISSUE TITLE
Remove 'PTC' as Signalling description.

### ISSUE THREAD

**Issue by STemplar** [OpenRailwayMap/OpenRailwayMap#846]
PTC is being used as a tag to display rail-lines in North America. But PTC is a generic term and not a specific system name.
This also means retagging a lot of the US lines.

Here are some of the installed systems in the US.
- **ACSES** (Advanced Civil Speed Enforcement System)
Amtrak's Northeast Corridor between Washington and Boston.

- **ASES** (Advanced Speed Enforcement System)
Ansaldo STS USA Inc system used on New Jersey Transit commuter lines, compatible with ACSES.

- **I-ETMS** (Interoperable Electronic Train Management System)
Wabtec system used by UP, BNSF, Metrolink and Caltrain.

- **ITCS** (Incremental Train Control System)
GE Transportation Systems wireless system implemented on the Amtrak Michigan line.

- **ATCS**: (Advanced Train Control System)
Sytem designed bij the AAR

**Comment by DerDakon** [comment]
While you are right, this is the wrong place to come up with this. Please propose a tagging for these systems and write down how they differ, i.e. if they are not just different names for the same thing.

I once started a proposal for different train protection systems here: https://wiki.openstreetmap.org/wiki/Proposal:Railway:train_protection
