### ISSUE TITLE
Train seen at 79mph in a 36mph zone

### ISSUE THREAD

**Issue by jidanni** [OpenRailwayMap/OpenRailwayMap#852]
![Screenshot_20230519_113033_All-In-One Offline Maps](https://github.com/OpenRailwayMap/OpenRailwayMap/assets/1230959/5139e5d1-3a51-4b76-99a8-77a47caf5f09)
So maybe the data needs to be updated. More:
![20230917T051710](https://github.com/OpenRailwayMap/OpenRailwayMap/assets/1230959/f5072e23-004a-4b69-9ca0-67efe89f0751)

**Comment by DerDakon** [comment]
OpenRailwayMap only renders the available data. You may add a note at https://www.openstreetmap.org or update the relevant data yourself if you can find out the correct speed value.

**Comment by jidanni** [comment]
Oh, I see. I was looking at the wrong layer.
"36" is the "ref", not the speed.
https://www.openstreetmap.org/way/175592145
