### ISSUE TITLE
Get reporting marks from Wikidata

### ISSUE THREAD

**Issue by marioxcc** [OpenRailwayMap/OpenRailwayMap#853]
When there is a `wikidata:operator` tag, get the reporting marks listed in Wikidata to reduce data duplication in OSM.

**Comment by wolfy1339** [comment]
The map doesn't display the reporting marks, that would be the first step even before this

**Comment by marioxcc** [comment]
I thought it does because I have seen “BNSF” in some track in North America. If it does not, then it must have been the `name`.

**Comment by wolfy1339** [comment]
Either it is not tagged correctly and the reporting marks are put in `ref`,
or it is in the `name` when there are 2 subdivisions with the same name with different owners/operators in the same geographic area.

**Comment by DerDakon** [comment]
What you see on the life map is rendered from the OpenRailwayMap-CartoCSS repository, but that also does not show any operator marks. So for now I'm going to close that as invalid as there is nothing about operators for now (beside owne change signs).
