### ISSUE TITLE
Consensus on tagging train stop based systems.

### ISSUE THREAD

**Issue by besentv** [OpenRailwayMap/OpenRailwayMap#859]
Currently many train stop based systems such as "Bernauer-Fahrsperre" and "CTS/M" (used by many subway systems) aren't properly tagged. The Wiki also doesn't mention how to tag them, so I wanted to use this issue to discuss what tags we want to use to do so. I have two proposals:

- Use a common tag for these systems, since they aren't highly sophisticated and all only serve the purpose to prevent running over a red signal. (MMTS = Mechanical and Magnetic train stop)
- Tag each system with it's own tag. (BEFS, CTSM, etc.)

**Comment by DerDakon** [comment]
Tagging issues must be discussed at the appropiate OSM places, e.g. wiki, forum, or tagging list. Issues here are only valid for the handling of tagging that is already agreed on.
